language: node_js

env: SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true CC=gcc-4.7 CXX=g++-4.7 LINK=gcc-4.7 LINKXX=g++-4.7

compiler: gcc

sudo: false

node_js:
  - "0.10"
  - "0.12"
  - "iojs-v1.0"
  - "iojs-v1"
  - "iojs-v2"
  - "iojs-v3"

matrix:
  fast_finish: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7

before_install:
  - g++ --version
  - git submodule update --init --recursive

after_success: npm run-script coverage

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8dddd234a441d0d07664
    on_success: change
