-
  branches:
    only:
      - release

  configuration: release

  platform:
    - x64
    - x86

  version: "{build}"
  build: off

  cache:  
    - c:\Users\appveyor\.node-gyp
    - '%AppData%\npm-cache'

  environment:
    SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true
    matrix:
      # node.js
      - nodejs_version: 0.10
      - nodejs_version: 0.12
      # io.js
      - nodejs_version: 1
      - nodejs_version: 2
      - nodejs_version: 3

  install:
    - ps: Install-Product node $env:nodejs_version $env:platform
    - node --version
    - npm --version
    - git submodule update --init --recursive
    - npm install --msvs_version=2013

  test_script: npm test

-
  configuration: testing

  platform:
    - x86

  version: "{build}"
  build: off

  cache:  
    - c:\Users\appveyor\.node-gyp
    - '%AppData%\npm-cache'

  environment:
    SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true
    matrix:
      # node.js
      - nodejs_version: 0.10
      - nodejs_version: 0.12
      # io.js
      - nodejs_version: 1
      - nodejs_version: 2
      - nodejs_version: 3

  install:
    - ps: Install-Product node $env:nodejs_version $env:platform
    - node --version
    - npm --version
    - git submodule update --init --recursive
    - npm install --msvs_version=2013

  test_script: npm test

