-
  os: Visual Studio 2015

  branches:
    only:
      - release

  configuration: release

  platform:
    - x86

  version: "{build}"

  build: off

  clone_folder: c:\projects\node_modules\node-sass

  init:
    - ps: gwmi win32_logicaldisk | % { $_.DeviceID }
    - cmd: >-
        echo About to subst

    - cmd: >-
        subst s: c:\projects

    - ps: gwmi win32_logicaldisk | % { $_.DeviceID }
    - ps: set-location -path s:\node_modules\node-sass

  on_finish:
    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

  cache:
    - '%userprofile%\.node-gyp'
    - '%AppData%\npm-cache'

  environment:
    SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true
    matrix:
      - nodejs_version: 5

  install:
    - ps: Install-Product node $env:nodejs_version $env:platform
    - node --version
    - npm --version
    - git submodule update --init --recursive
    - npm install --msvs_version=2015

  test_script: npm test

  before_deploy:
    # Save artifacts with full qualified names of binding.node and binding.pdb
    # (which we use in node-sass-binaries repo)
    - ps: >-
        Get-ChildItem .\vendor\**\*.node | % {
           ( $BindingName = $_.FullName ).Split('\\') |
             Select-Object -Last 2 | Select-Object -First 1 } |
               .{ process { (
                  @( $BindingName,
                       ( ( $_, "binding.node" ) -join '_' ) ),
                  @( ".\build\Release\binding.pdb", 
                       ( ( $_, "binding.pdb" ) -join '_' ) )
               ) } } | % { Push-AppveyorArtifact $_[0] -FileName $_[1] }

  deploy:
    - provider: GitHub
      description: $(APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)
      artifact:
      auth_token:
        secure: tt+p58W9Q49faww/o0CODJI8e++YEX5THVlpXlRIigO4xHjE8NKigi0oxr1b2PJE
      on:
        branch: release               # release from master branch only
        appveyor_repo_tag: true       # deploy on tag push only


-
  os: Visual Studio 2015

  configuration: testing

  platform:
    - x86

  version: "{build}"

  build: off

  init:
    - mkdir c:\project\node_modules
    - subst s: c:\project\node_modules

  clone_folder: s:\node_modules\node-sass

  cache:
    - '%userprofile%\.node-gyp'
    - '%AppData%\npm-cache'

  environment:
    SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true
    matrix:
      - nodejs_version: 0.10
      - nodejs_version: 0.12
      - nodejs_version: 1
      - nodejs_version: 2
      - nodejs_version: 3
      - nodejs_version: 4

  install:
    - ps: Install-Product node $env:nodejs_version $env:platform
    - node --version
    - npm --version
    - git submodule update --init --recursive
    - npm install --msvs_version=2015

  test_script: npm test
